Lint/HandleExceptions:
  Exclude:
    - rakelib/*.rake

Documentation:
    Enabled: false

Metrics/ClassLength:
  CountComments: false # count full line comments?
  Max: 150

Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading
  Enabled: true

Style/ExtraSpacing:
   Enabled: false
